language:
  - objective-c

before_install:
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew tap homebrew/homebrew-php

install:
  - brew install php55
  - brew install composer

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./src/Mystem --standard=PSR1 --encoding=utf-8 --report=summary
  - php vendor/bin/phpcs ./src/Mystem --standard=PSR2 --encoding=utf-8 --report=summary
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration tests/phpunit.xml.dist --coverage-clover=.reports/clover.xml

after_success:
  # Send cover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml

git:
  depth: 1

notifications:
  email:
    - travis-mystem@aotd.ru