language:
  - objective-c

notifications:
  email:
    - travis-mystem@aotd.ru

before_install:
  - brew update

install:
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew install homebrew/php/php53
  - brew install composer
  - brew install parallel

before_script:
  - composer install --prefer-source
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - ls -d tests/Mystem/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/phpunit.xml.dist {};' || exit 1

git:
  depth: 1